CREATE PROCEDURE sp_load_account
AS
BEGIN
	SELECT USERNAME AS N'Tài khoản',DISPLAY_NAME AS N'Tên hiển thị', PASSWORD AS N'Mật khẩu', TYPE_ACCOUNT AS N'Loại tài khoản' FROM ACCOUNT
END
GO

CREATE PROCEDURE sp_load_tableF
AS
BEGIN
	SELECT NAME as N'Tên bàn', STT as N'Trạng thái', TOTAL as N'Tổng tiền' FROM TABLEF
END
GO

CREATE PROCEDURE sp_load_billinfo
@NAME_TABLE nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAME_TABLE = @NAME_TABLE
END
GO

CREATE PROCEDURE sp_load_category
AS
BEGIN
	SELECT NAME as N'Tên danh mục' FROM CATEGORY
END
GO

CREATE PROCEDURE sp_load_food 
@NAME_CATEGORY nvarchar(100)
AS
BEGIN
	SELECT NAME as N'Tên món', NAME_CATEGORY as N'Tên DM', PRICE as N'Giá'  FROM FOOD WHERE NAME_CATEGORY = @NAME_CATEGORY
END
GO
CREATE PROCEDURE sp_load_AllFood 
AS
BEGIN
	SELECT NAME as N'Tên món', NAME_CATEGORY as N'Tên DM', PRICE as N'Giá'  FROM FOOD
END
GO

CREATE PROCEDURE sp_datban
@NAME_TABLE nvarchar(100)
,@STT nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = @STT WHERE NAME = @NAME_TABLE
END
GO

CREATE PROCEDURE sp_Add_Account
@USERNAME nvarchar(100)
,@DISPLAY_NAME nvarchar(100)
,@PASSWORD nvarchar(100)
,@TYPE_ACCOUNT nvarchar(100)
AS
BEGIN
	INSERT INTO ACCOUNT (USERNAME,DISPLAY_NAME,PASSWORD,TYPE_ACCOUNT) VALUES (@USERNAME,@DISPLAY_NAME,@PASSWORD,@TYPE_ACCOUNT)
END
GO
CREATE PROCEDURE sp_Del_Account
@USERNAME nvarchar(100)
AS
BEGIN
	DELETE FROM ACCOUNT WHERE USERNAME LIKE @USERNAME
END
GO
CREATE PROCEDURE sp_Update_Account
@USERNAME nvarchar(100)
,@DISPLAY_NAME nvarchar(100)
,@PASSWORD nvarchar(100)
,@TYPE_ACCOUNT nvarchar(100)
,@Where_USERNAME nvarchar(100)
AS
BEGIN
	UPDATE ACCOUNT SET USERNAME = @USERNAME, DISPLAY_NAME = @DISPLAY_NAME, PASSWORD = @PASSWORD, TYPE_ACCOUNT = @TYPE_ACCOUNT WHERE USERNAME = @Where_USERNAME
END
GO

CREATE PROCEDURE sp_add_food
@NAME_CATEGORY nvarchar(100)
,@NAME nvarchar(100)
,@PRICE float
AS
BEGIN
	INSERT INTO FOOD (NAME_CATEGORY, NAME, PRICE) VALUES (@NAME_CATEGORY,@NAME,@PRICE)
END
GO
CREATE PROCEDURE sp_del_food
@NAME_CATEGORY nvarchar(100)
AS
BEGIN
	DELETE FROM FOOD WHERE NAME LIKE @NAME_CATEGORY
END
GO
CREATE PROCEDURE sp_update_food
@NAME_CATEGORY nvarchar(100)
,@NAME nvarchar(100)
,@PRICE float
,@Where_NAME nvarchar(100)
AS
BEGIN
	UPDATE FOOD SET NAME = @NAME, NAME_CATEGORY = @NAME_CATEGORY, PRICE = @PRICE WHERE NAME = @Where_NAME
END
GO

CREATE PROCEDURE sp_add_table
@NAME nvarchar(100)
AS
BEGIN
	INSERT INTO TABLEF(NAME,STT,TOTAL) VALUES (@NAME,N'TRONG',0)
END
GO
CREATE PROCEDURE sp_del_table
@NAME nvarchar(100)
AS
BEGIN
	DELETE FROM TABLEF WHERE NAME = @NAME
END
GO
CREATE PROCEDURE sp_update_table
@NAME nvarchar(100)
,@Where_NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET NAME = @NAME WHERE NAME = @Where_NAME
END
GO

--Doi mon
CREATE PROCEDURE sp_table_food_bill
@NAME nvarchar(100)
AS
BEGIN
	SELECT BILL.NAME_FOOD, BILL.COUNTS, FOOD.PRICE, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAME_TABLE JOIN FOOD ON BILL.NAME_FOOD = FOOD.NAME WHERE TABLEF.NAME like @NAME
END
GO
CREATE PROCEDURE sp_sua_sl_mon
@NAMEF nvarchar(100)
,@NAMET nvarchar(100)
,@count int
AS
BEGIN
	UPDATE BILL SET COUNTS = @count WHERE NAME_TABLE like @NAMET AND NAME_FOOD like @NAMEF
END
GO
CREATE PROCEDURE sp_sua_total
@NAMET nvarchar(100)
,@total float
AS
BEGIN
	UPDATE TABLEF SET TOTAL = @total WHERE NAME like @NAMET
END
GO


CREATE PROCEDURE sp_move_food
@NAME_TABLE nvarchar(100)
,@NAME_FOOD nvarchar(100)
,@COUNTS int
AS
BEGIN
	INSERT INTO BILL(NAME_TABLE,NAME_FOOD,COUNTS) VALUES (@NAME_TABLE,@NAME_FOOD,@COUNTS)
END
GO

CREATE PROCEDURE sp_move_table
@TOTAL float
,@NAMET nvarchar(100)
,@NAMEF nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'ONLINE', TOTAL = @TOTAL WHERE NAME like @NAMET;
	UPDATE TABLEF SET STT = N'TRONG', TOTAL = 0 WHERE NAME like @NAMEF ;
	DELETE FROM BILL WHERE NAME_TABLE like @NAMEF ;
END
GO
CREATE PROCEDURE sp_check_table
@NAMET nvarchar(100)
AS
BEGIN
	SELECT BILL.NAME_FOOD, BILL.COUNTS, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAME_TABLE WHERE TABLEF.NAME like @NAMET 
END
GO

CREATE PROCEDURE sp_add_category
@NAMEC nvarchar(100)
AS
BEGIN
	INSERT INTO CATEGORY(NAME) VALUES (@NAMEC);
END
GO
CREATE PROCEDURE sp_Del_category
@NAMEC nvarchar(100)
AS
BEGIN
	DELETE FROM CATEGORY WHERE NAME like @NAMEC
END
GO
CREATE PROCEDURE sp_Update_category
@NAMEC nvarchar(100)
,@Where_CATEGORY nvarchar(100)
AS
BEGIN
	UPDATE CATEGORY SET NAME = @NAMEC WHERE NAME like @Where_CATEGORY
END
GO


CREATE PROCEDURE sp_load_food_table
@NAMET nvarchar(100)
AS
BEGIN
	SELECT BILL.NAME_FOOD, BILL.COUNTS, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAME_TABLE WHERE TABLEF.NAME like @NAMET;
END
GO

CREATE PROCEDURE sp_gop_Table
@NAME_TABLE_A nvarchar(100)
,@NAME_TABLE_B nvarchar(100)
,@addTotal float
AS
BEGIN
	UPDATE TABLEF SET STT = N'TRONG', TOTAL = 0 WHERE NAME like @NAME_TABLE_A;
	DELETE FROM BILL WHERE NAME_TABLE like @NAME_TABLE_A;
	UPDATE TABLEF SET STT = N'ONLINE', TOTAL += @addTotal WHERE NAME like @NAME_TABLE_B;
END
GO


CREATE PROCEDURE sp_load_table_where
@NAME nvarchar(100)
AS
BEGIN
	SELECT * FROM TABLEF WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_load_bill_where
@NAME nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAME_TABLE like @NAME
END
GO
CREATE PROCEDURE sp_clear_table
@NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'TRONG', TOTAL = 0 WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_clear_bill
@NAME nvarchar(100)
AS
BEGIN
	DELETE FROM BILL WHERE NAME_TABLE = @NAME
END
GO
CREATE PROCEDURE sp_reset_table
@NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'ONLINE' WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_them_mon
@NAME nvarchar(100)
,@NAME_FOOD nvarchar(100)
,@COUNT int
AS
BEGIN
	INSERT INTO BILL(NAME_TABLE,NAME_FOOD,COUNTS) VALUES (@NAME, @NAME_FOOD, @COUNT);
END
GO
CREATE PROCEDURE sp_tang_slmon
@NAME nvarchar(100)
,@NAME_FOOD nvarchar(100)
,@COUNT int
AS
BEGIN
	UPDATE BILL SET COUNTS += @COUNT WHERE NAME_TABLE like @NAME AND NAME_FOOD like @NAME_FOOD;
END
GO
CREATE PROCEDURE sp_check_food_table
@NAME nvarchar(100)
,@NAME_FOOD nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAME_TABLE like @NAME AND NAME_FOOD like @NAME_FOOD
END
GO
CREATE PROCEDURE sp_get_price
@NAME_FOOD nvarchar(100)
AS
BEGIN
	SELECT PRICE FROM FOOD WHERE NAME like @NAME_FOOD
END
GO
CREATE PROCEDURE sp_set_total
@NAME nvarchar(100)
,@total float
AS
BEGIN
	UPDATE TABLEF SET TOTAL += @total WHERE NAME like @NAME
END
GO


CREATE PROCEDURE sp_reset_account
@NAME nvarchar(100)
,@PASS nvarchar(100)
, @DISPLAY_NAME nvarchar(100)
AS
BEGIN
	UPDATE ACCOUNT SET DISPLAY_NAME = @DISPLAY_NAME, PASSWORD = @PASS WHERE USERNAME = @NAME;
END
GO